# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/volonter/kona

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/volonter/kona

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/volonter/kona/CMakeFiles /home/volonter/kona/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/volonter/kona/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named k

# Build rule for target.
k : cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 k
.PHONY : k

# fast build rule for target.
k/fast:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/build
.PHONY : k/fast

src/0.o: src/0.c.o
.PHONY : src/0.o

# target to build an object file
src/0.c.o:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/0.c.o
.PHONY : src/0.c.o

src/0.i: src/0.c.i
.PHONY : src/0.i

# target to preprocess a source file
src/0.c.i:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/0.c.i
.PHONY : src/0.c.i

src/0.s: src/0.c.s
.PHONY : src/0.s

# target to generate assembly for a file
src/0.c.s:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/0.c.s
.PHONY : src/0.c.s

src/c.o: src/c.c.o
.PHONY : src/c.o

# target to build an object file
src/c.c.o:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/c.c.o
.PHONY : src/c.c.o

src/c.i: src/c.c.i
.PHONY : src/c.i

# target to preprocess a source file
src/c.c.i:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/c.c.i
.PHONY : src/c.c.i

src/c.s: src/c.c.s
.PHONY : src/c.s

# target to generate assembly for a file
src/c.c.s:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/c.c.s
.PHONY : src/c.c.s

src/d.o: src/d.c.o
.PHONY : src/d.o

# target to build an object file
src/d.c.o:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/d.c.o
.PHONY : src/d.c.o

src/d.i: src/d.c.i
.PHONY : src/d.i

# target to preprocess a source file
src/d.c.i:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/d.c.i
.PHONY : src/d.c.i

src/d.s: src/d.c.s
.PHONY : src/d.s

# target to generate assembly for a file
src/d.c.s:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/d.c.s
.PHONY : src/d.c.s

src/getline.o: src/getline.c.o
.PHONY : src/getline.o

# target to build an object file
src/getline.c.o:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/getline.c.o
.PHONY : src/getline.c.o

src/getline.i: src/getline.c.i
.PHONY : src/getline.i

# target to preprocess a source file
src/getline.c.i:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/getline.c.i
.PHONY : src/getline.c.i

src/getline.s: src/getline.c.s
.PHONY : src/getline.s

# target to generate assembly for a file
src/getline.c.s:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/getline.c.s
.PHONY : src/getline.c.s

src/k.o: src/k.c.o
.PHONY : src/k.o

# target to build an object file
src/k.c.o:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/k.c.o
.PHONY : src/k.c.o

src/k.i: src/k.c.i
.PHONY : src/k.i

# target to preprocess a source file
src/k.c.i:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/k.c.i
.PHONY : src/k.c.i

src/k.s: src/k.c.s
.PHONY : src/k.s

# target to generate assembly for a file
src/k.c.s:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/k.c.s
.PHONY : src/k.c.s

src/kapi.o: src/kapi.c.o
.PHONY : src/kapi.o

# target to build an object file
src/kapi.c.o:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/kapi.c.o
.PHONY : src/kapi.c.o

src/kapi.i: src/kapi.c.i
.PHONY : src/kapi.i

# target to preprocess a source file
src/kapi.c.i:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/kapi.c.i
.PHONY : src/kapi.c.i

src/kapi.s: src/kapi.c.s
.PHONY : src/kapi.s

# target to generate assembly for a file
src/kapi.c.s:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/kapi.c.s
.PHONY : src/kapi.c.s

src/kc.o: src/kc.c.o
.PHONY : src/kc.o

# target to build an object file
src/kc.c.o:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/kc.c.o
.PHONY : src/kc.c.o

src/kc.i: src/kc.c.i
.PHONY : src/kc.i

# target to preprocess a source file
src/kc.c.i:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/kc.c.i
.PHONY : src/kc.c.i

src/kc.s: src/kc.c.s
.PHONY : src/kc.s

# target to generate assembly for a file
src/kc.c.s:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/kc.c.s
.PHONY : src/kc.c.s

src/kg.o: src/kg.c.o
.PHONY : src/kg.o

# target to build an object file
src/kg.c.o:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/kg.c.o
.PHONY : src/kg.c.o

src/kg.i: src/kg.c.i
.PHONY : src/kg.i

# target to preprocess a source file
src/kg.c.i:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/kg.c.i
.PHONY : src/kg.c.i

src/kg.s: src/kg.c.s
.PHONY : src/kg.s

# target to generate assembly for a file
src/kg.c.s:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/kg.c.s
.PHONY : src/kg.c.s

src/km.o: src/km.c.o
.PHONY : src/km.o

# target to build an object file
src/km.c.o:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/km.c.o
.PHONY : src/km.c.o

src/km.i: src/km.c.i
.PHONY : src/km.i

# target to preprocess a source file
src/km.c.i:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/km.c.i
.PHONY : src/km.c.i

src/km.s: src/km.c.s
.PHONY : src/km.s

# target to generate assembly for a file
src/km.c.s:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/km.c.s
.PHONY : src/km.c.s

src/kn.o: src/kn.c.o
.PHONY : src/kn.o

# target to build an object file
src/kn.c.o:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/kn.c.o
.PHONY : src/kn.c.o

src/kn.i: src/kn.c.i
.PHONY : src/kn.i

# target to preprocess a source file
src/kn.c.i:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/kn.c.i
.PHONY : src/kn.c.i

src/kn.s: src/kn.c.s
.PHONY : src/kn.s

# target to generate assembly for a file
src/kn.c.s:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/kn.c.s
.PHONY : src/kn.c.s

src/ko.o: src/ko.c.o
.PHONY : src/ko.o

# target to build an object file
src/ko.c.o:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/ko.c.o
.PHONY : src/ko.c.o

src/ko.i: src/ko.c.i
.PHONY : src/ko.i

# target to preprocess a source file
src/ko.c.i:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/ko.c.i
.PHONY : src/ko.c.i

src/ko.s: src/ko.c.s
.PHONY : src/ko.s

# target to generate assembly for a file
src/ko.c.s:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/ko.c.s
.PHONY : src/ko.c.s

src/ks.o: src/ks.c.o
.PHONY : src/ks.o

# target to build an object file
src/ks.c.o:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/ks.c.o
.PHONY : src/ks.c.o

src/ks.i: src/ks.c.i
.PHONY : src/ks.i

# target to preprocess a source file
src/ks.c.i:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/ks.c.i
.PHONY : src/ks.c.i

src/ks.s: src/ks.c.s
.PHONY : src/ks.s

# target to generate assembly for a file
src/ks.c.s:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/ks.c.s
.PHONY : src/ks.c.s

src/kx.o: src/kx.c.o
.PHONY : src/kx.o

# target to build an object file
src/kx.c.o:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/kx.c.o
.PHONY : src/kx.c.o

src/kx.i: src/kx.c.i
.PHONY : src/kx.i

# target to preprocess a source file
src/kx.c.i:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/kx.c.i
.PHONY : src/kx.c.i

src/kx.s: src/kx.c.s
.PHONY : src/kx.s

# target to generate assembly for a file
src/kx.c.s:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/kx.c.s
.PHONY : src/kx.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/main.c.s
.PHONY : src/main.c.s

src/mt.o: src/mt.c.o
.PHONY : src/mt.o

# target to build an object file
src/mt.c.o:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/mt.c.o
.PHONY : src/mt.c.o

src/mt.i: src/mt.c.i
.PHONY : src/mt.i

# target to preprocess a source file
src/mt.c.i:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/mt.c.i
.PHONY : src/mt.c.i

src/mt.s: src/mt.c.s
.PHONY : src/mt.s

# target to generate assembly for a file
src/mt.c.s:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/mt.c.s
.PHONY : src/mt.c.s

src/p.o: src/p.c.o
.PHONY : src/p.o

# target to build an object file
src/p.c.o:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/p.c.o
.PHONY : src/p.c.o

src/p.i: src/p.c.i
.PHONY : src/p.i

# target to preprocess a source file
src/p.c.i:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/p.c.i
.PHONY : src/p.c.i

src/p.s: src/p.c.s
.PHONY : src/p.s

# target to generate assembly for a file
src/p.c.s:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/p.c.s
.PHONY : src/p.c.s

src/r.o: src/r.c.o
.PHONY : src/r.o

# target to build an object file
src/r.c.o:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/r.c.o
.PHONY : src/r.c.o

src/r.i: src/r.c.i
.PHONY : src/r.i

# target to preprocess a source file
src/r.c.i:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/r.c.i
.PHONY : src/r.c.i

src/r.s: src/r.c.s
.PHONY : src/r.s

# target to generate assembly for a file
src/r.c.s:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/r.c.s
.PHONY : src/r.c.s

src/v.o: src/v.c.o
.PHONY : src/v.o

# target to build an object file
src/v.c.o:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/v.c.o
.PHONY : src/v.c.o

src/v.i: src/v.c.i
.PHONY : src/v.i

# target to preprocess a source file
src/v.c.i:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/v.c.i
.PHONY : src/v.c.i

src/v.s: src/v.c.s
.PHONY : src/v.s

# target to generate assembly for a file
src/v.c.s:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/v.c.s
.PHONY : src/v.c.s

src/va.o: src/va.c.o
.PHONY : src/va.o

# target to build an object file
src/va.c.o:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/va.c.o
.PHONY : src/va.c.o

src/va.i: src/va.c.i
.PHONY : src/va.i

# target to preprocess a source file
src/va.c.i:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/va.c.i
.PHONY : src/va.c.i

src/va.s: src/va.c.s
.PHONY : src/va.s

# target to generate assembly for a file
src/va.c.s:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/va.c.s
.PHONY : src/va.c.s

src/vc.o: src/vc.c.o
.PHONY : src/vc.o

# target to build an object file
src/vc.c.o:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/vc.c.o
.PHONY : src/vc.c.o

src/vc.i: src/vc.c.i
.PHONY : src/vc.i

# target to preprocess a source file
src/vc.c.i:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/vc.c.i
.PHONY : src/vc.c.i

src/vc.s: src/vc.c.s
.PHONY : src/vc.s

# target to generate assembly for a file
src/vc.c.s:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/vc.c.s
.PHONY : src/vc.c.s

src/vd.o: src/vd.c.o
.PHONY : src/vd.o

# target to build an object file
src/vd.c.o:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/vd.c.o
.PHONY : src/vd.c.o

src/vd.i: src/vd.c.i
.PHONY : src/vd.i

# target to preprocess a source file
src/vd.c.i:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/vd.c.i
.PHONY : src/vd.c.i

src/vd.s: src/vd.c.s
.PHONY : src/vd.s

# target to generate assembly for a file
src/vd.c.s:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/vd.c.s
.PHONY : src/vd.c.s

src/vf.o: src/vf.c.o
.PHONY : src/vf.o

# target to build an object file
src/vf.c.o:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/vf.c.o
.PHONY : src/vf.c.o

src/vf.i: src/vf.c.i
.PHONY : src/vf.i

# target to preprocess a source file
src/vf.c.i:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/vf.c.i
.PHONY : src/vf.c.i

src/vf.s: src/vf.c.s
.PHONY : src/vf.s

# target to generate assembly for a file
src/vf.c.s:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/vf.c.s
.PHONY : src/vf.c.s

src/vg.o: src/vg.c.o
.PHONY : src/vg.o

# target to build an object file
src/vg.c.o:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/vg.c.o
.PHONY : src/vg.c.o

src/vg.i: src/vg.c.i
.PHONY : src/vg.i

# target to preprocess a source file
src/vg.c.i:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/vg.c.i
.PHONY : src/vg.c.i

src/vg.s: src/vg.c.s
.PHONY : src/vg.s

# target to generate assembly for a file
src/vg.c.s:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/vg.c.s
.PHONY : src/vg.c.s

src/vq.o: src/vq.c.o
.PHONY : src/vq.o

# target to build an object file
src/vq.c.o:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/vq.c.o
.PHONY : src/vq.c.o

src/vq.i: src/vq.c.i
.PHONY : src/vq.i

# target to preprocess a source file
src/vq.c.i:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/vq.c.i
.PHONY : src/vq.c.i

src/vq.s: src/vq.c.s
.PHONY : src/vq.s

# target to generate assembly for a file
src/vq.c.s:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/src/vq.c.s
.PHONY : src/vq.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... k"
	@echo "... src/0.o"
	@echo "... src/0.i"
	@echo "... src/0.s"
	@echo "... src/c.o"
	@echo "... src/c.i"
	@echo "... src/c.s"
	@echo "... src/d.o"
	@echo "... src/d.i"
	@echo "... src/d.s"
	@echo "... src/getline.o"
	@echo "... src/getline.i"
	@echo "... src/getline.s"
	@echo "... src/k.o"
	@echo "... src/k.i"
	@echo "... src/k.s"
	@echo "... src/kapi.o"
	@echo "... src/kapi.i"
	@echo "... src/kapi.s"
	@echo "... src/kc.o"
	@echo "... src/kc.i"
	@echo "... src/kc.s"
	@echo "... src/kg.o"
	@echo "... src/kg.i"
	@echo "... src/kg.s"
	@echo "... src/km.o"
	@echo "... src/km.i"
	@echo "... src/km.s"
	@echo "... src/kn.o"
	@echo "... src/kn.i"
	@echo "... src/kn.s"
	@echo "... src/ko.o"
	@echo "... src/ko.i"
	@echo "... src/ko.s"
	@echo "... src/ks.o"
	@echo "... src/ks.i"
	@echo "... src/ks.s"
	@echo "... src/kx.o"
	@echo "... src/kx.i"
	@echo "... src/kx.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mt.o"
	@echo "... src/mt.i"
	@echo "... src/mt.s"
	@echo "... src/p.o"
	@echo "... src/p.i"
	@echo "... src/p.s"
	@echo "... src/r.o"
	@echo "... src/r.i"
	@echo "... src/r.s"
	@echo "... src/v.o"
	@echo "... src/v.i"
	@echo "... src/v.s"
	@echo "... src/va.o"
	@echo "... src/va.i"
	@echo "... src/va.s"
	@echo "... src/vc.o"
	@echo "... src/vc.i"
	@echo "... src/vc.s"
	@echo "... src/vd.o"
	@echo "... src/vd.i"
	@echo "... src/vd.s"
	@echo "... src/vf.o"
	@echo "... src/vf.i"
	@echo "... src/vf.s"
	@echo "... src/vg.o"
	@echo "... src/vg.i"
	@echo "... src/vg.s"
	@echo "... src/vq.o"
	@echo "... src/vq.i"
	@echo "... src/vq.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

